/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-03-25 20:06:55 UTC)
 * on 2016-04-07 at 02:10:33 UTC 
 * Modify at your own risk.
 */

package com.appspot.party_queue_1243.party_queue.model;

/**
 * ProtoRPC message def. for creating/getting a playlist
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the party_queue. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PartyQueueApiMessagesPlaylistRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String firstsong;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long pid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userid;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFirstsong() {
    return firstsong;
  }

  /**
   * @param firstsong firstsong or {@code null} for none
   */
  public PartyQueueApiMessagesPlaylistRequest setFirstsong(java.lang.String firstsong) {
    this.firstsong = firstsong;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public PartyQueueApiMessagesPlaylistRequest setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPid() {
    return pid;
  }

  /**
   * @param pid pid or {@code null} for none
   */
  public PartyQueueApiMessagesPlaylistRequest setPid(java.lang.Long pid) {
    this.pid = pid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserid() {
    return userid;
  }

  /**
   * @param userid userid or {@code null} for none
   */
  public PartyQueueApiMessagesPlaylistRequest setUserid(java.lang.Long userid) {
    this.userid = userid;
    return this;
  }

  @Override
  public PartyQueueApiMessagesPlaylistRequest set(String fieldName, Object value) {
    return (PartyQueueApiMessagesPlaylistRequest) super.set(fieldName, value);
  }

  @Override
  public PartyQueueApiMessagesPlaylistRequest clone() {
    return (PartyQueueApiMessagesPlaylistRequest) super.clone();
  }

}
