/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-03-25 20:06:55 UTC)
 * on 2016-04-07 at 02:10:33 UTC 
 * Modify at your own risk.
 */

package com.appspot.party_queue_1243.party_queue.model;

/**
 * Model definition for PartyQueueApiMessagesSongMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the party_queue. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PartyQueueApiMessagesSongMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("spotify_id")
  private java.lang.String spotifyId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("vote_count") @com.google.api.client.json.JsonString
  private java.lang.Long voteCount;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public PartyQueueApiMessagesSongMessage setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSpotifyId() {
    return spotifyId;
  }

  /**
   * @param spotifyId spotifyId or {@code null} for none
   */
  public PartyQueueApiMessagesSongMessage setSpotifyId(java.lang.String spotifyId) {
    this.spotifyId = spotifyId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVoteCount() {
    return voteCount;
  }

  /**
   * @param voteCount voteCount or {@code null} for none
   */
  public PartyQueueApiMessagesSongMessage setVoteCount(java.lang.Long voteCount) {
    this.voteCount = voteCount;
    return this;
  }

  @Override
  public PartyQueueApiMessagesSongMessage set(String fieldName, Object value) {
    return (PartyQueueApiMessagesSongMessage) super.set(fieldName, value);
  }

  @Override
  public PartyQueueApiMessagesSongMessage clone() {
    return (PartyQueueApiMessagesSongMessage) super.clone();
  }

}
